//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_STUDIES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic_process
    {
        public int Academic_process_id { get; set; }
        public Nullable<int> Score_id { get; set; }
        public string Academic_Message { get; set; }
    
        public virtual Score_details Score_details { get; set; }
    }
}
