//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_STUDIES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_us
    {
        public int Contact_us_id { get; set; }
        public Nullable<int> userid { get; set; }
        public string Subjects { get; set; }
        public string Contact_us_messages { get; set; }
        public string email { get; set; }
    
        public virtual User User { get; set; }
    }
}
