//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_STUDIES.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class estudiezEntities : DbContext
    {
        public estudiezEntities()
            : base("name=estudiezEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Academic_process> Academic_process { get; set; }
        public virtual DbSet<Contact_us> Contact_us { get; set; }
        public virtual DbSet<Parents_data> Parents_data { get; set; }
        public virtual DbSet<Revision_classes> Revision_classes { get; set; }
        public virtual DbSet<Score_details> Score_details { get; set; }
        public virtual DbSet<Student_data> Student_data { get; set; }
        public virtual DbSet<Study_resources> Study_resources { get; set; }
        public virtual DbSet<Teacher_data> Teacher_data { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
    
        public virtual ObjectResult<Parents_data_sp_Result> Parents_data_sp(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Parents_data_sp_Result>("Parents_data_sp", useridParameter);
        }
    
        public virtual ObjectResult<Student_data_sp_Result> Student_data_sp(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Student_data_sp_Result>("Student_data_sp", useridParameter);
        }
    
        public virtual ObjectResult<Teacher_data_sp_Result> Teacher_data_sp(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Teacher_data_sp_Result>("Teacher_data_sp", useridParameter);
        }
    
        public virtual int ChangeStatus(Nullable<int> id, Nullable<bool> resource_status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var resource_statusParameter = resource_status.HasValue ?
                new ObjectParameter("resource_status", resource_status) :
                new ObjectParameter("resource_status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeStatus", idParameter, resource_statusParameter);
        }
    
        public virtual int ChangeStatus1(Nullable<int> id, Nullable<bool> res_status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var res_statusParameter = res_status.HasValue ?
                new ObjectParameter("res_status", res_status) :
                new ObjectParameter("res_status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeStatus1", idParameter, res_statusParameter);
        }
    
        public virtual int ChangeStatus2(Nullable<int> id, Nullable<bool> resource_status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var resource_statusParameter = resource_status.HasValue ?
                new ObjectParameter("resource_status", resource_status) :
                new ObjectParameter("resource_status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeStatus2", idParameter, resource_statusParameter);
        }
    }
}
