//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_STUDIES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents_data
    {
        public int Parents_data_id { get; set; }
        public string Parent_Name { get; set; }
        public Nullable<long> phone { get; set; }
        public string Cnic { get; set; }
        public string Parents_address { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual User User { get; set; }
    }
}
