//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_STUDIES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision_classes
    {
        public int Revision_class_id { get; set; }
        public Nullable<System.DateTime> Class_start_date { get; set; }
        public Nullable<System.TimeSpan> Class_time { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual User User { get; set; }
    }
}
