//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_STUDIES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Score_details()
        {
            this.Academic_process = new HashSet<Academic_process>();
        }
    
        public int Score_id { get; set; }
        public Nullable<int> Total_Marks { get; set; }
        public Nullable<int> Score_receive { get; set; }
        public Nullable<System.DateTime> Issued_date { get; set; }
        public string Score_description { get; set; }
        public Nullable<int> userid { get; set; }
        public string course { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Academic_process> Academic_process { get; set; }
        public virtual User User { get; set; }
    }
}
