//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_STUDIES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_data
    {
        public int Student_data_id { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> Enrollment_date { get; set; }
        public string Student_address { get; set; }
        public Nullable<int> Student_age { get; set; }
        public Nullable<long> phone { get; set; }
        public string Student_image { get; set; }
        public Nullable<int> Teacher_data_id { get; set; }
        public Nullable<int> userid { get; set; }
        public string Gender { get; set; }
    
        public virtual Teacher_data Teacher_data { get; set; }
        public virtual User User { get; set; }
    }
}
